### ISSUE TITLE
Where is FlatGreenScreen? 

### ISSUE THREAD

**Issue by wushujian** [MiloMindbender/UE4VirtualProduction#12]
Not find in this codes.

**Comment by MiloMindbender** [comment]
The FlatGreenScreen is just an actor that represents my real world green screen as two flat planes.  There is no code/blueprints associated with this.  In the sample level you will see it in the world outliner if you search for "flat" or if you look in the content browser under content/VPStudioCore/Models.  This is only used to create the matte composure uses to cut out areas the camera might see that are outside of your greenscreen.  You can adjust this to most any size screen.  If your greenscreen isn't flat (like it might be a "corner", box or curved shape) you can make a model of your own green screen that has the right shape and substitute it.  Just use simple white polygons, no textures/shading/materials needed.

**Comment by wushujian** [comment]
thank you very much!

**Comment by MiloMindbender** [comment]
problem solved
